apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-latency
  namespace: monitoring
spec:
  groups:
    - name: app.rules
      rules:
        - alert: HighRequestLatency
          expr: |
            histogram_quantile(
              0.95,
              rate(http_request_duration_seconds_bucket[5m])
            ) > 1
          for: 3m
          labels:
            severity: warning
          annotations:
            summary: "High application latency"
            description: "95th percentile latency > 1s for 3 minutes."
